config/routes.rb
Rails.application.routes.draw do
  

  root 'home#index'
  get 'contacto/index'
  get 'servicio/index'
  get 'nosotros/index'
  get 'home/index'
  get 'pedido/index'
  get 'localmenu/index'
  get 'locales/index'
  get 'registrousuario/index'
  get 'perfil/index'

end

app/models/district.rb
class District < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :password
    
    email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
    
    validates :name, :presence     => true,
              :length              => { :maximum => 100 }
    
    validates :email, :presence    => true,
              :format              => {:with => email_regex},
              :uniqueness          => { :case_sensitive => false}
    
    validates :password, :presence => true,
              :confirmation        => true,
              :length              => { :within => 6..20 }
    
    before_save :encrypt_password

    # Ruby on rails 4 ya no utiliza el attr_accessible ahora es el Strong Parameters
    #attr_accessible :name, :address, :district_id, :email, :estate, :password, :password_confirmation
    # Strong Parameters
    def user_params
        params.require(:user).permit(:name, :address, :district_id, :email, :estate, :password, :password_confirmation)
    end
    
    def has_password?(submitted_password)
        encrypted_password == encrypt(submitted_password)
    end

    #Chequea si el email y el password son válidos
    def self.authenticate(email, submitted_password)
        user = find_by_email(email)

        return nil if user.nil?
        return user if user.has_password?(submitted_password)
    end
    
    private
        def encrypt_password
            self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
            self.encrypted_password= encrypt(password)
        end
        
        def encrypt(pass)
            Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
        end
end

app/controllers/contacto_controller.rb
class ContactoController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController
  def index
  end
end

app/controllers/nosotros_controller.rb
class NosotrosController < ApplicationController
  def index
  end
end

app/controllers/pedido_controller.rb
class PedidoController < ApplicationController
  def index
  end
end

app/controllers/perfil_controller.rb
class PerfilController < ApplicationController
  def index
  end
end

app/controllers/servicio_controller.rb
class ServicioController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new 
    end
    
    def create
        @user = User.new(params[:user])
        if @user.save
            redirect_to @user, notice: 'Grabación exitosa'
        else
            render action: "new"
        end
    end
      
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacto_helper.rb
module ContactoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/localmenu_helper.rb
module LocalmenuHelper
end

app/helpers/nosotros_helper.rb
module NosotrosHelper
end

app/helpers/pedido_helper.rb
module PedidoHelper
end

app/helpers/perfil_helper.rb
module PerfilHelper
end

app/helpers/registrousuario_helper.rb
module RegistrousuarioHelper
end

app/helpers/servicio_helper.rb
module ServicioHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def sign_in(user)
        session[:user_is] = user.id
        self.current_user = user
    end
    
    def current_user=(user)
        @current_user = user
    end
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[user_id]
    end
    
    def signed_in?
        !current_user.nil
    end
    
    def sign_out
        session[:user_id] = nil
        self.current_user = nil
    end
    
    def current_user?(user)
        user == current_user
    end
    
    def deny_access
        redirect_to signin_path, :notice => "Tiene acceso a esta página."
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacto/index.html.erb
<div id="cuerpo" class="cuerpo">
    <h1 style="margin:0px 20px 10px;">Contáctenos</h1>
    <hr>
    <div>
        <div id="dialogo" class="modal-box">
            <header style="width:303px;">
                <a href="#" class="js-modal-close close">×</a>
                <h3>Mensaje</h3>
            </header>
            <div class="modal-body">
                <p>Mensaje enviado.</p>
            </div>
            <footer><a href="#" class="js-modal-close botonahref">Cerrar</a></footer>
        </div>
        <form>
            <div style="  margin: 15px auto;width: 450px;">
                <table width="100%" cellspacing="15">
                    <tr>
                        <td width="15%">
                            <label for="">Nombre</label>
                        </td>     
                        <td width="85%">
                            <input size="65" type="text" style="width: 330px;" name="" value=""/>
                        </td> 
                    </tr>
                    <tr>
                        <td>
                            <label for="">Correo</label>
                        </td>     
                        <td>
                            <input size="65" type="text" style="width: 330px;" name="" value=""/>
                        </td> 
                    </tr>
                    <tr>
                        <td>
                            <label for="">Teléfono</label>
                        </td>     
                        <td>
                            <input size="30" type="text" style="width: 180px;" name="" value=""/>
                        </td> 
                    </tr>
                    <tr style="vertical-align:top;">
                        <td>
                            <label for="">Mensaje</label>
                        </td>     
                        <td>
                            <textarea cols="15" rows="5"></textarea>
                        </td> 
                    </tr>
                </table>
            </div>
            <div>
                <div style="margin-bottom: 10px;">
                    <table width="40%" style="margin:auto;">
                        <tr>
                            <td width="120px" height="35px" align="right">
                                <a href="#" class="js-open-modal botonahref" data-modal-id="dialogo" style="width: 100px;">Grabar</a>
                            </td>
                            <td width="10%"> </td>
                            <td width="120px" height="35px" align="right">
                                <%= link_to 'Limpiar', '#', onclick: 'clearForm(this.form);', class: "link_to" %>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </form>
        <input type="button" name="" style="width: 150px;margin-left: 150px;" value="Mostrar ubicación" onclick="getLocation()"/>
        <div id="map" style="padding-bottom: 15px;"></div>
    </div>
</div>
<script>
    $(function(){
        var appendthis = ("<div class='modal-overlay js-modal-close'></div>");
        $('a[data-modal-id]').click(function(e) {
    		e.preventDefault();
            $("body").append(appendthis);
            $(".modal-overlay").fadeTo(500, 0.7);
            //$(".js-modalbox").fadeIn(500);
        	var modalBox = $(this).attr('data-modal-id');
        	$('#'+modalBox).fadeIn($(this).data());
        });  
        	
        $(".js-modal-close, .modal-overlay").click(function() {
            $(".modal-box, .modal-overlay").fadeOut(500, function() {
                $(".modal-overlay").remove();
            });
        });
        
        $(window).resize(function() {
            $(".modal-box").css({
                top: ($(window).height() - $(".modal-box").outerHeight()) / 2,
                left: ($(window).width() - $(".modal-box").outerWidth()) / 2
            });
        });
        
        $(window).resize();
    });
</script>

app/views/home/index.html.erb
<div id="cuerpo" class="cuerpo">
    <h1 style="margin:0px 20px 10px;">Bienvenido</h1>
    <hr>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <div>
        <div class="bloque">
            <div class="bloquecomida">
                <div><%= link_to (image_tag "food/food1.jpg", width:"100%"), localmenu_index_path %></a></div>
                <p><span class="tex1">Food1</span><span class="tex2">S/.13.00</span></p>
            </div>
            <div class="bloquecomida">
                <div><%= link_to (image_tag "food/food2.jpg", width:"100%"), localmenu_index_path %></a></div>
                <p><span class="tex1">Food2</span><span class="tex2">S/.10.00</span></p>
            </div>
        </div>
    </div>
</div>

app/views/locales/index.html.erb
<div id="cuerpo" class="cuerpo">
    <h1 style="margin:0px 20px 10px;">Restaurantes encontrados</h1>
    <hr>
    <div style="margin: 15px 30px 30px 20px;">
        <div class="bloque">
            <div class="imagenrestaurant" style="margin: 20px 0 20px 20px;"><%= link_to (image_tag "rest1.jpg", width:"100%"), localmenu_index_path %></div>
            <div class="detallerestaurant" style="width: 450px;margin: 15px 0px 10px 20px;">
                <h4>Nombre del loca</h4>
                <p>Dirección</p>
                <p>Teléfono</p>
                <p>Correo electrónico</p>
                <div style="text-align: right;">
                    <%= link_to 'Ver menú', localmenu_index_path, class: "link_to" %>
                </div>
            </div>
        </div>
        <div class="bloque">
            <div class="imagenrestaurant" style="margin: 20px 0 20px 20px;"><%= link_to (image_tag "rest1.jpg", width:"100%"), localmenu_index_path %></div>
            <div class="detallerestaurant" style="width: 450px;margin: 15px 0px 10px 20px;">
                <h4>Nombre del loca</h4>
                <p>Dirección</p>
                <p>Teléfono</p>
                <p>Correo electrónico</p>
                <div style="text-align: right;">
                    <%= link_to 'Ver menú', localmenu_index_path, class: "link_to" %>
                </div>
            </div>
        </div>
        <div class="bloque">
            <div class="imagenrestaurant" style="margin: 20px 0 20px 20px;"><%= link_to (image_tag "rest1.jpg", width:"100%"), localmenu_index_path %></div>
            <div class="detallerestaurant" style="width: 450px;margin: 15px 0px 10px 20px;">
                <h4>Nombre del loca</h4>
                <p>Dirección</p>
                <p>Teléfono</p>
                <p>Correo electrónico</p>
                <div style="text-align: right;">
                    <%= link_to 'Ver menú', localmenu_index_path, class: "link_to" %>
                </div>
            </div>
        </div>
        <div class="bloque" style="border-bottom: 0px;">
            <div class="imagenrestaurant" style="margin: 20px 0 20px 20px;"><%= link_to (image_tag "rest1.jpg", width:"100%"), localmenu_index_path %></div>
            <div class="detallerestaurant" style="width: 450px;margin: 15px 0px 10px 20px;">
                <h4>Nombre del loca</h4>
                <p>Dirección</p>
                <p>Teléfono</p>
                <p>Correo electrónico</p>
                <div style="text-align: right;">
                    <%= link_to 'Ver menú', localmenu_index_path, class: "link_to" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/nosotros/index.html.erb
<div id="cuerpo" class="cuerpo">
    <h1 style="margin:0px 20px 10px;">Nosotros</h1>
    <hr>
    <p>
        El ambiente minimalista que se respira acerca al comensal a lo esencial de la gastronomía,
        la sencillez de la belleza y el buen gusto que se complementa con vajilla Philipe des Soliers,
        mobiliario Andreu World, vestuario Lechienerrant, diferentes iluminaciones en cada espacio y
        sala privada para las reuniones más exigentes, un broche de oro a esta propuesta única en la ciudad.
    </p>
    <div>
        <%= image_tag "equipo.png" %>
    </div>
</div>

app/views/pedido/index.html.erb
<div id="cuerpo" class="cuerpo">
    <h1 style="margin:0px 20px 10px;">Consolidado del Pedido</h1>
    <hr>
    <div style="margin: 15px 30px 0px 30px;">
        <div id="dialogo" class="modal-box" style="top: 339px; left: 382px;">
            <header style="width:303px;">
                <a href="#" class="js-modal-close close">×</a>
                <h3>Mensaje</h3>
            </header>
            <div class="modal-body">
                <p>Grabación exitosa.</p>
            </div>
            <footer><a href="#" class="js-modal-close botonahref">Cerrar</a></footer>
        </div>                        
        <div>
            <table width="100%">
                <tr height="30px">
                    <th style="background-color:#799839;color:#fff;font-size: 16px;width: 280px;">PEDIDO</th>
                    <th style="background-color:#799839;color:#fff;font-size: 16px;width: 60px;">CANTIDAD</th>
                    <th style="background-color:#799839;color:#fff;font-size: 16px;width: 60px;">PRECIO</th>
                    <th style="background-color:#799839;color:#fff;font-size: 16px;width: 60px;">TOTAL</th>
                <tr height="30">
                    <td style="background-color:#748A37;color:#fff;">Entrada</td>
                    <td style="background-color:#748A37;color:#fff;"></td>
                    <td style="background-color:#748A37;color:#fff;"></td>
                    <td style="background-color:#748A37;color:#fff;"></td>
                </tr>
                <tr>
                    <td style="background-color:#E1EACC;font-size:14px;">E1) Chicharrón de pollo c/yuquitas... </td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">
                        <input type="text" name="" value="1" style="width:20px; text-align:center;"/>
                    </td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">S/. 6.00</td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">S/. 6.00</td>
                </tr>
                <tr>
                    <td style="background-color:#E1EACC;font-size:14px;">E2) Sopa de menestron </td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">
                        <input type="text" name="" value="1" style="width:20px; text-align:center;"/>
                    </td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">S/. 6.00</td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">S/. 6.00</td>
                </tr>
                <tr>
                    <td style="background-color:#E1EACC;font-size:14px;">E3) Causa de pollo </td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">
                        <input type="text" name="" value="1" style="width:20px; text-align:center;"/>
                    </td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">S/. 6.00</td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">S/. 6.00</td>
                </tr>
                <tr height="30">
                    <td style="background-color:#748A37;color:#fff;">Segundos</td>
                    <td style="background-color:#748A37;color:#fff;"></td>
                    <td style="background-color:#748A37;color:#fff;"></td>
                    <td style="background-color:#748A37;color:#fff;"></td>
                </tr>
                <tr>
                    <td style="background-color:#E1EACC;font-size:14px;">S1) Seco de res a la norteña c/frejoles</td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">
                        <input type="text" name="" value="1" style="width:20px; text-align:center;"/>
                    </td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">S/. 8.50 </td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">S/. 8.50 </td>
                </tr>
                <tr>
                    <td style="background-color:#E1EACC;font-size:14px;">S2) Pollo dorado c/papas fritas y ensalada</td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">
                        <input type="text" name="" value="1" style="width:20px; text-align:center;"/>
                    </td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">S/. 8.50 </td>
                    <td align="center" style="background-color:#E1EACC;font-size:14px;">S/. 8.50 </td>
                </tr>
                <tr height="30">
                    <td style="background-color:#748A37;color:#fff;">Total de entradas</td>
                    <td align="center" style="background-color:#748A37;color:#fff;">3</td>
                    <td style="background-color:#748A37;color:#fff;"></td>
                    <td style="background-color:#748A37;color:#fff;"></td>
                </tr>    
                <tr height="30">
                    <td style="background-color:#748A37;color:#fff;">Total de segundos</td>
                    <td align="center" style="background-color:#748A37;color:#fff;">2</td>
                    <td style="background-color:#748A37;color:#fff;"></td>
                    <td style="background-color:#748A37;color:#fff;"></td>
                </tr> 
                <tr height="30" >
                    <td colspan="3" style="background-color:#748A37;color:#fff;">Total</td>
                    <td align="center" style="background-color:#748A37;color:#fff;">S/.35.00</td>
                </tr> 
            </table>
            <form name="data_entry" id="data_entry_frm" action="#">
                <div>
                    <table width="100%" cellspacing="15">
                        <tr>
                            <td width="15%">
                                <label for="">Nombre</label>
                            </td>     
                            <td width="85%">
                                <input size="30" type="text" style="width: 490px;" name="" value=""/>
                            </td> 
                        </tr>
                        <tr>
                            <td>
                                <label for="">Correo</label>
                            </td>     
                            <td>
                                <input size="30"  type="text" style="width: 490px;" name="" value=""/>
                            </td> 
                        </tr>
                        <tr>
                            <td>
                                <label for="">Dirección</label>
                            </td>     
                            <td>
                                <input size="30" type="text" style="width: 490px;" name="" value=""/>
                            </td> 
                        </tr>
                        <tr>
                            <td>
                                <label for="">Distrito</label>
                            </td>     
                            <td>
                                <select style="width: 250px;">
                                    <option select>Selecciona distrito</option>
                                    <option>San Isidro</option>
                                    <option>La Victoria</option>
                                </select>
                            </td>     
                        </tr>
                    </table>
                </div>
                <div style="margin-bottom: 10px;">
                    <table width="40%" style="margin:auto;">
                        <tr>
                            <td width="120px" height="35px" align="right">
                                <a href="#" class="js-open-modal botonahref" data-modal-id="dialogo" style="width: 100px;">Grabar</a>
                            </td>
                            <td width="10%"> </td>
                            <td width="120px" height="35px" align="right">
                                <input type="button" name="" value="Limpiar" onclick="clearForm(this.form);"/>
                            </td>
                        </tr>
                    </table>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    $(function(){
        var appendthis = ("<div class='modal-overlay js-modal-close'></div>");
        $('a[data-modal-id]').click(function(e) {
    		e.preventDefault();
            $("body").append(appendthis);
            $(".modal-overlay").fadeTo(500, 0.7);
            //$(".js-modalbox").fadeIn(500);
        	var modalBox = $(this).attr('data-modal-id');
        	$('#'+modalBox).fadeIn($(this).data());
        });  
        	
        $(".js-modal-close, .modal-overlay").click(function() {
            $(".modal-box, .modal-overlay").fadeOut(500, function() {
                $(".modal-overlay").remove();
            });
        });
        
        $(window).resize(function() {
            $(".modal-box").css({
                top: ($(window).height() - $(".modal-box").outerHeight()) / 2,
                left: ($(window).width() - $(".modal-box").outerWidth()) / 2
            });
        });
        
        $(window).resize();
    });
</script>